import type { DealTotals } from "@/lib/calc";
import type { Deal } from "@/lib/validators";
import { money, num } from "@/lib/format";
import { evaluateDealHealth } from "@/lib/dealHealth";

/**
 * Generate a plain text summary of deal metrics for sharing via Slack/email
 */
export function generatePlainTextSummary(deal: Deal, totals: DealTotals): string {
  const date = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });

  // Evaluate deal health
  const health = evaluateDealHealth(deal);
  const healthStatus = health.status === 'strong' ? 'Strong' : health.status === 'ok' ? 'OK' : 'Risky';
  const healthEmoji =
    health.status === 'strong' ? '🟢' :
    health.status === 'ok' ? '🟡' :
    '🔴';

  // Build product summary
  const products = deal.products
    .filter(p => p.includeInTotals)
    .map((p, i) => {
      if (p.type === 'RECURRING') {
        return `  ${i + 1}. ${p.name} - ${money(p.listPricePerUnitMonthly)}/mo × ${p.licenses} licenses`;
      } else {
        return `  ${i + 1}. ${p.name} - ${money(p.oneTimeListPrice)} (one-time)`;
      }
    })
    .join('\n');

  return `
📊 DEAL SUMMARY: ${deal.name}
Generated ${date}

${healthEmoji} DEAL HEALTH: ${healthStatus}
${health.positives.map(s => `  ✓ ${s}`).join('\n') || ''}
${health.concerns.map(c => `  ⚠ ${c}`).join('\n') || ''}

💰 CORE METRICS
  ARR: ${money(totals.annualizedRevenue)}
  MRR: ${money(totals.effectiveMRR)}
  TCV: ${money(totals.tcv)}

📈 PROFITABILITY
  Net Margin: ${totals.blendedMarginPct !== null ? `${totals.blendedMarginPct.toFixed(1)}%` : 'N/A'}
  Total Profit: ${money(totals.termProfit)}

🎯 ADVANCED METRICS
  LTV:CAC Ratio: ${totals.ltvToCac !== null ? num(totals.ltvToCac, 2) : 'N/A'}
  Payback Period: ${totals.paybackMonths !== null ? totals.paybackMonths.toFixed(1) + ' months' : 'N/A'}

📦 PRODUCTS (${deal.products.filter(p => p.includeInTotals).length})
${products}

⚙️ DEAL TERMS
  Contract Length: ${totals.termMonths} months
  Billing Cadence: ${deal.billingCadence === 'MONTHLY' ? 'Monthly' : 'Annual Prepay'}
${deal.toggles.includeCAC ? `  Customer Acquisition Cost: ${money(deal.cac)}` : ''}

───────────────────────────────
Generated by DealQuary
  `.trim();
}

/**
 * Copy text to clipboard with fallback for older browsers
 */
export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    // Modern clipboard API
    await navigator.clipboard.writeText(text);
    return true;
  } catch (error) {
    // Fallback for older browsers or when clipboard API is blocked
    try {
      const textarea = document.createElement('textarea');
      textarea.value = text;
      textarea.style.position = 'fixed';
      textarea.style.opacity = '0';
      document.body.appendChild(textarea);
      textarea.select();
      const success = document.execCommand('copy');
      document.body.removeChild(textarea);
      return success;
    } catch {
      console.error('Failed to copy to clipboard:', error);
      return false;
    }
  }
}
